### ISSUE TITLE
doesn't wanna work with samsung devices

### ISSUE THREAD

**Issue by KaliFoxy** [twrpdtgen/twrpdtgen#140]
the recovery image used was for a125m

this is the output
`$ python3 -m twrpdtgen recovery.img
TWRP device tree generator
Version 3.0.0

[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kenn/.local/lib/python3.10/site-packages/twrpdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/kenn/.local/lib/python3.10/site-packages/twrpdtgen/main.py", line 37, in main
    device_tree = DeviceTree(image=args.image)
  File "/home/kenn/.local/lib/python3.10/site-packages/twrpdtgen/device_tree.py", line 56, in __init__
    self.image_info = self.aik_manager.unpackimg(image)
  File "/home/kenn/.local/lib/python3.10/site-packages/sebaubuntu_libs/libaik/__init__.py", line 122, in unpackimg
    raise RuntimeError(f"AIK extraction failed, return code {returncode}")
RuntimeError: AIK extraction failed, return code 1`

**Comment by SebaUbuntu** [comment]
🤷‍♂️
