### ISSUE TITLE
Getting errors even after manually adding files.

### ISSUE THREAD

**Issue by sounddrill31** [twrpdtgen/twrpdtgen#154]
Device: micromax a109. 
Uploaded recovery: CWM auto-generated, same problem happens with stock recovery. Note: I manually added values(and repackaged using carliv) to fix previous errors.

I added the following values to default.prop:
```
ro.bootimage.product.cpu.abilist=armeabi
ro.product.first_api_level=15
ro.build.version.security_patch=146

```

I'm probably doing something wrong

```
@sounddrill31 ➜ /workspaces/twrpdtgen/workshop (master) $ python3 -m twrpdtgen modified.img 
TWRP device tree generator
Version 3.0.0

[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/codespace/.python/current/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/twrpdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/twrpdtgen/main.py", line 37, in main
    device_tree = DeviceTree(image=args.image)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/twrpdtgen/device_tree.py", line 75, in __init__
    self.fstab = Fstab(fstab)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/fstab/__init__.py", line 58, in __init__
    self.entries.append(FstabEntry.from_entry(line))
  File "/home/codespace/.python/current/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/fstab/__init__.py", line 41, in from_entry
    src, mount_point, fs_type, mnt_flags, fs_flags = line.split()
ValueError: not enough values to unpack (expected 5, got 3)
@sounddrill31 ➜ /workspaces/twrpdtgen/workshop (master) $ 
```

**Comment by sounddrill31** [comment]
Never mind, I was doing something wrong. I used stock recovery and it worked well smh
