### ISSUE TITLE
AssertionError: Couldn't find any build.prop

### ISSUE THREAD

**Issue by keywordsyt** [twrpdtgen/twrpdtgen#159]
this is the error I got : python3 -m twrpdtgen ./boot.img 
TWRP device tree generator
Version 1.3.0

[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pavan_shardings_com/.local/lib/python3.7/site-packages/twrpdtgen/__main__.py", line 55, in <module>
    recovery_ramdisk=args.recovery_ramdisk, recovery_vendor=args.recovery_vendor)
  File "/home/pavan_shardings_com/.local/lib/python3.7/site-packages/twrpdtgen/device_tree.py", line 57, in __init__
    raise AssertionError("Couldn't find any build.prop")
AssertionError: Couldn't find any build.prop

and my boot image is : https://xfl.jp/xa9WF5

I have extracted this image from realme 5 pro's ozip file downloaded from this website : https://www.realme.com/in/support/software-update

if you can could you please slove this issue Thanks for your contribution

**Comment by SebaUbuntu** [comment]
Blame your OEM
