### ISSUE TITLE
`twrpdtgen` does not work in Python 3.12

### ISSUE THREAD

**Issue by soulspark666** [twrpdtgen/twrpdtgen#161]
While trying to execute 

```python
 ~\Desktop\dt> python -m twrpdtgen .\boot.img
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Animesh\AppData\Local\Programs\Python\Python312\Lib\site-packages\twrpdtgen\main.py", line 8, in <module>
    from twrpdtgen.main import main
  File "C:\Users\Animesh\AppData\Local\Programs\Python\Python312\Lib\site-packages\twrpdtgen\main.py", line 11, in <module>
    from twrpdtgen.device_tree import DeviceTree
  File "C:\Users\Animesh\AppData\Local\Programs\Python\Python312\Lib\site-packages\twrpdtgen\device_tree.py", line 12, in <module>
    from sebaubuntu_libs.libandroid.device_info import DeviceArch, DeviceInfo
  File "C:\Users\Animesh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sebaubuntu_libs\libandroid\device_info.py", line 7, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
```

Upon further [investigation](https://stackoverflow.com/a/76691103), it seems:
![untitled](https://github.com/twrpdtgen/twrpdtgen/assets/37495396/d781fcad-bab2-463f-9873-9dc1d73a4e44)

Where it can bee seen that `distutils` is deprecated: https://peps.python.org/pep-0632/

So it seems this will not hold true now:
![untitled](https://github.com/twrpdtgen/twrpdtgen/assets/37495396/e771d697-04d0-4575-83cd-6b4872a0f5f7)

**Comment by Shubthedeveloper** [comment]
Remove latest python
Reinstall python 3.12 
Try pip install  twrpgen

**Comment by SebaUbuntu** [comment]
Fixed in sebaubuntu_libs
