### ISSUE TITLE
error when lanchung

### ISSUE THREAD

**Issue by dzwdev** [twrpdtgen/twrpdtgen#190]
this is the output:
```
sudo python3 -m twrpdtgen stock_L09_pie9.img

TWRP device tree generator
Version 3.0.0

[INFO] Cloning AIK...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/twrpdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/twrpdtgen/main.py", line 37, in main
    device_tree = DeviceTree(image=args.image)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/twrpdtgen/device_tree.py", line 55, in __init__
    self.aik_manager = AIKManager()
                       ^^^^^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/.venv/lib/python3.11/site-packages/sebaubuntu_libs/libaik/__init__.py", line 105, in __init__
    Repo.clone_from(AIK_REPO, self.path)
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/.venv/lib/python3.11/site-packages/git/repo/base.py", line 1405, in clone_from
    return cls._clone(
           ^^^^^^^^^^^
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/.venv/lib/python3.11/site-packages/git/repo/base.py", line 1302, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/.venv/lib/python3.11/site-packages/git/util.py", line 483, in finalize_process
    proc.wait(**kwargs)
  File "/home/pc/Downloads/Huawei P10 VTR-L09/compile twrp/twrpdtgen-master/.venv/lib/python3.11/site-packages/git/cmd.py", line 657, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/SebaUbuntu/AIK-Linux-mirror /tmp/tmpyxauk_cs
  stderr: 'Cloning into '/tmp/tmpyxauk_cs'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (217 bytes)
error: 3957 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

```

**Comment by SebaUbuntu** [comment]
Get a better internet connection
