### ISSUE TITLE
AssertionError: Property ro.product.system.device could not be found in build.prop

### ISSUE THREAD

**Issue by super020gamer** [twrpdtgen/twrpdtgen#195]
TWRP device tree generator
Version 3.0.0

[INFO] Cloning AIK...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/twrpdtgen/__main__.py", line 11, in <module>
    main()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/twrpdtgen/main.py", line 37, in main
    device_tree = DeviceTree(image=args.image)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/twrpdtgen/device_tree.py", line 66, in __init__
    self.device_info = DeviceInfo(self.build_prop)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/sebaubuntu_libs/libandroid/device_info.py", line 120, in __init__
    self.codename = self.get_first_prop(DEVICE_CODENAME)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/sebaubuntu_libs/libandroid/device_info.py", line 185, in get_first_prop
    raise AssertionError(f'Property {props[0]} could not be found in build.prop')
AssertionError: Property ro.product.system.device could not be found in build.prop

This is the boot img
https://download843.mediafire.com/88sh3xpbhylgUdl2E0Gs-BGxnPyotDG-WaGu0VPb8u4bRjIb8eVm1ymZDQ7puvml8PCdU4UpZYe2lnzr2x9hfesVVrD_JjOGTTK8SpOcT_YomRdRKoeTN3bRLVxkd23qqH0xirwbS_Dqxteyn3xGTjmzTRkV9wMM2YzrILWeF70/308fmqs5inv5n9w/boot.img

**Comment by super020gamer** [comment]
Edit:used vendor_boot and worked
