### ISSUE TITLE
Failing When Extracting AIK

### ISSUE THREAD

**Issue by Nottotallynadawr** [twrpdtgen/twrpdtgen#206]
Hello, When i Tried To Generate The Device Tree Generator It Returns This Error While Cloning AIK
Log Displayed:
```
TWRP device tree generator
Version 3.0.0

[INFO] Cloning AIK...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nadawr/.local/lib/python3.12/site-packages/twrpdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/nadawr/.local/lib/python3.12/site-packages/twrpdtgen/main.py", line 37, in main
    device_tree = DeviceTree(image=args.image)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadawr/.local/lib/python3.12/site-packages/twrpdtgen/device_tree.py", line 56, in __init__
    self.image_info = self.aik_manager.unpackimg(image)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadawr/.local/lib/python3.12/site-packages/sebaubuntu_libs/libaik/__init__.py", line 132, in unpackimg
    raise RuntimeError(f"AIK extraction failed, return code {returncode}")
RuntimeError: AIK extraction failed, return code 1
```
.img used: https://drive.google.com/file/d/1P9BPJY-ZWSnAmaI6TBVsAvTdNINEVlhc/view?usp=drive_link

**Comment by Nottotallynadawr** [comment]
nvm, it was the boot.img being faulty
