### ISSUE TITLE
2.1. 2075 build,prop 

### ISSUE THREAD

**Issue by bgman111111** [twrpdtgen/twrpdtgen#98]
sudo python3 -m twrpdtgen recovery.img -d
[sudo] password for popravki: 
TWRP device tree generator
Version 2.1.0

[aikmanager.py:54 DEBUG] __init__: Cloning AIK...
[cmd.py:869 DEBUG] execute: Popen(['git', 'clone', '-v', 'https://github.com/SebaUbuntu/AIK-Linux-mirror', '/home/popravki/Downloads/AIK-Linux-v3.8-ALL/t/extract'], cwd=/home/popravki/Downloads/AIK-Linux-v3.8-ALL/t, universal_newlines=True, shell=None, istream=None)
[base.py:1085 DEBUG] _clone: Cmd(['git', 'clone', '-v', 'https://github.com/SebaUbuntu/AIK-Linux-mirror', '/home/popravki/Downloads/AIK-Linux-v3.8-ALL/t/extract'])'s unused stdout: 
[devicetree.py:51 DEBUG] __init__: Getting device infos...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/twrpdtgen/__main__.py", line 6, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/twrpdtgen/main.py", line 31, in main
    device_tree = DeviceTree(image=args.image, debug=args.debug)
  File "/usr/local/lib/python3.9/dist-packages/twrpdtgen/devicetree.py", line 59, in __init__
    raise AssertionError("Couldn't find any build.prop")
AssertionError: Couldn't find any build.prop
recovery.img : https://bgzashtita.es/android/11.img

**Comment by SebaUbuntu** [comment]
Same as #110
